name: "docker-publish-action"
description: "Publishes an image to Docker Hub"
inputs:
  docker-image:
    description: "name of the image (example: fsouza/fake-gcs-server)"
    required: true
  docker-username:
    description: "Username to authenticate with Docker Hub"
    required: false
  docker-password:
    description: "Password to authenticate with Docker Hub"
    required: false
  dockerfile:
    description: "Path to the dockerfile (defaults to Dockerfile)"
    required: false
    default: "Dockerfile"

runs:
  using: "composite"
  steps:
    - name: docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.docker-image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: setup qemu
      uses: docker/setup-qemu-action@v1

    - name: setup buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
