name: "docker-publish-action"
description: "Publishes an image to Docker Hub"
inputs:
  docker-image:
    description: "name of the image (example: fsouza/fake-gcs-server)"
    required: true
  docker-username:
    description: "Username to authenticate with Docker Hub"
    required: false
  docker-password:
    description: "Password to authenticate with Docker Hub"
    required: false
  skip-push:
    description: "Whether to skip push (useful for pull-requests, to test the image building process)"
    required: false
    default: "false"
  dockerfile:
    description: "Path to the dockerfile (defaults to Dockerfile)"
    required: false
    default: "Dockerfile"
  tag:
    description: "Additional tag on top of 'latest'. Can be inferred from git if used on the correct event"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/docker-build.sh
      shell: bash
      env:
        DOCKERFILE: ${{ inputs.dockerfile }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        DOCKER_PASSWORD: ${{ inputs.docker-password }}
        DOCKER_USERNAME: ${{ inputs.docker-username }}
        SKIP_PUSH: ${{ inputs.skip-push }}
        TAG: ${{ inputs.tag }}
