name: Build
on:
  schedule:
    - cron: "21 2 * * 2"

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-push:
    name: test-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: test push
        if: github.event_name == 'push'
        uses: ./
        with:
          dockerfile: tests/Dockerfile
          docker-image: fsouzaci/docker-publish-action-test
          docker-username: fsouzaci
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
