name: Build
on:
  schedule:
    - cron: "21 2 * * 2"

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Test the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - run: shellcheck docker-build.sh

      - uses: ./
        with:
          docker-image: fsouza/fake-gcs-server
          dockerfile: tests/Dockerfile
          skip-push: true
